import { Open_Sans, Unna } from 'next/font/google'
import Header from '../components/Header'
import Footer from '../components/Footer'

import { Providers } from '../GlobalRedux/provider'

import '@/app/styles/global.css'

export const metadata = {
  title: 'e-commerce',
  description: 'Generated by create next app',
}

const OpenSans = Open_Sans ({
  weight:  ['400', '700'],
  subsets: ['latin'],
  variable: '--font-open-sans',
})

const UnnaRegular = Unna ({
  weight:  ['400', '700'],
  subsets: ['latin'],
  variable: '--font-unna',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className={`${UnnaRegular.variable} ${OpenSans.variable}`}>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
        </body>
    </html>
  )
}
