import { Open_Sans } from 'next/font/google'
import Header from '../components/Header'

import '@/app/styles/global.css'

export const metadata = {
  title: 'e-commerce',
  description: 'Generated by create next app',
}

const OpenSans = Open_Sans ({
  weight:  ['400', '700'],
  subsets: ['latin'],
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className={OpenSans.className}>
        <Header />
        {children}
        </body>
    </html>
  )
}
